name: openai_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_udid: ^3.0.0
  font_awesome_flutter: ^10.7.0
  http: ^1.2.1
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
  adaptive_icon_foreground: "assets/logo/logo.png"

flutter:
  uses-material-design: true
  assets:
  - .env
