// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9224JRI_sotbv_XR6fLraikU7VYBV300',
    appId: '1:1080983970935:web:8732d4d60a0f719e699272',
    messagingSenderId: '1080983970935',
    projectId: 'ai-pal-11875',
    authDomain: 'ai-pal-11875.firebaseapp.com',
    storageBucket: 'ai-pal-11875.appspot.com',
    measurementId: 'G-7ZXXJNJXC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvON1zuTSa4ZgSb7QzexJlsoXvb8ajENw',
    appId: '1:1080983970935:android:d5a943346414f294699272',
    messagingSenderId: '1080983970935',
    projectId: 'ai-pal-11875',
    storageBucket: 'ai-pal-11875.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFhLUdVTltOPGikB5aSj4imfToIOWkA_c',
    appId: '1:1080983970935:ios:52eea4ec5e5f2a8d699272',
    messagingSenderId: '1080983970935',
    projectId: 'ai-pal-11875',
    storageBucket: 'ai-pal-11875.appspot.com',
    iosBundleId: 'com.example.openaiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFhLUdVTltOPGikB5aSj4imfToIOWkA_c',
    appId: '1:1080983970935:ios:52eea4ec5e5f2a8d699272',
    messagingSenderId: '1080983970935',
    projectId: 'ai-pal-11875',
    storageBucket: 'ai-pal-11875.appspot.com',
    iosBundleId: 'com.example.openaiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9224JRI_sotbv_XR6fLraikU7VYBV300',
    appId: '1:1080983970935:web:f1a59dab4b3df18b699272',
    messagingSenderId: '1080983970935',
    projectId: 'ai-pal-11875',
    authDomain: 'ai-pal-11875.firebaseapp.com',
    storageBucket: 'ai-pal-11875.appspot.com',
    measurementId: 'G-QHMV206XR6',
  );
}
